# Generated by Django 4.2.27 on 2025-12-13 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('origin', models.CharField(blank=True, max_length=50, verbose_name='Xuất xứ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Danh mục cha')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('fullname', models.CharField(max_length=100, verbose_name='Người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='SĐT')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('total_money', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Tổng tiền hàng')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phí ship')),
                ('final_money', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Thành tiền')),
                ('payment_method', models.CharField(default='COD', max_length=50, verbose_name='PT Thanh toán')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('order_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Trả hàng')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Mã SKU')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá gốc')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá khuyến mãi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh đại diện')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='Album ảnh (JSON)')),
                ('target_skin_type', models.CharField(default='Mọi loại da', max_length=50, verbose_name='Phù hợp loại da')),
                ('main_ingredients', models.TextField(blank=True, verbose_name='Thành phần chính')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='Hướng dẫn sử dụng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Tổng tồn kho')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Đã bán')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('status', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=20, verbose_name='SĐT')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh/Thành')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('detail_address', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mặc định')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='Số sao')),
                ('comment', models.TextField(verbose_name='Bình luận')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Ảnh feedback (JSON)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order', verbose_name='Mua từ đơn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, verbose_name='Mã lô')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng lô này')),
                ('manufacturing_date', models.DateField(verbose_name='Ngày sản xuất')),
                ('expiry_date', models.DateField(verbose_name='Hạn sử dụng')),
                ('import_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Giá nhập')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên SP (Lưu cứng)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá bán lúc mua')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productbatch', verbose_name='Xuất từ Lô')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('skin_type', models.CharField(choices=[('unknown', 'Chưa xác định'), ('oily', 'Da dầu'), ('dry', 'Da khô'), ('combination', 'Da hỗn hợp'), ('normal', 'Da thường'), ('sensitive', 'Da nhạy cảm')], default='unknown', max_length=20, verbose_name='Loại da')),
                ('skin_concerns', models.JSONField(blank=True, default=list, verbose_name='Vấn đề về da (JSON)')),
                ('role', models.IntegerField(choices=[(0, 'Khách hàng'), (1, 'Admin'), (2, 'Nhân viên')], default=0, verbose_name='Vai trò')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
        ),
    ]
