# Generated by Django 4.2.27 on 2025-12-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence_score',
            field=models.FloatField(default=0.0, verbose_name='Độ tin cậy AI'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('POS', 'Tích cực'), ('NEU', 'Trung tính'), ('NEG', 'Tiêu cực')], default='NEU', max_length=3, verbose_name='Cảm xúc AI'),
        ),
    ]
