# Generated by Django 4.2.27 on 2026-01-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_review_confidence_score_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='Là spam'),
        ),
        migrations.AddField(
            model_name='review',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lý do spam'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('POS', 'Tích cực'), ('NEU', 'Trung tính'), ('NEG', 'Tiêu cực'), ('SPAM', 'Spam')], default='NEU', max_length=4, verbose_name='Cảm xúc AI'),
        ),
    ]
