# Generated by Django 4.2.27 on 2026-01-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review_is_spam_review_spam_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='Từ khóa spam')),
                ('category', models.CharField(choices=[('FINANCE', 'Tài chính/Cho vay'), ('CONTACT', 'Liên hệ/Quảng cáo'), ('EXTERNAL', 'Link bên ngoài'), ('FAKE', 'Hàng giả/Hàng nhái'), ('REPEAT', 'Lặp từ/Spam'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Danh mục')),
                ('severity', models.IntegerField(default=100, help_text='100 = Spam chắc chắn, 50 = Nghi ngờ', verbose_name='Độ nghiêm trọng (0-100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('description', models.TextField(blank=True, help_text='Giải thích tại sao là spam', verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Từ khóa spam',
                'verbose_name_plural': 'Danh sách từ khóa spam',
                'ordering': ['-severity', 'keyword'],
            },
        ),
    ]
