# Generated by Django 4.2.27 on 2026-02-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_spamkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hot Deal Cuối Tuần', max_length=100, verbose_name='Tiêu đề deal')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Phụ đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('deal_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá deal')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('max_quantity', models.IntegerField(default=0, help_text='0 = Không giới hạn', verbose_name='Số lượng giới hạn')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Đã bán')),
                ('deal_image', models.ImageField(blank=True, null=True, upload_to='deals/', verbose_name='Ảnh deal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('priority', models.IntegerField(default=0, help_text='Số lớn = Ưu tiên cao', verbose_name='Độ ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ưu đãi cuối tuần',
                'verbose_name_plural': 'Danh sách ưu đãi',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
